export const shortCaptions = [
  "Wrapped in your love.",
  "Under the same stars, love shines.",
  "Hugs, cocoa, and you.",
  "Merry everything, and a happy always.",
  "Love, lights, and laughter.",
  "Home is wherever I'm with you.",
  "Together makes everything better.",
  "Christmas magic in your eyes.",
  "Forever grateful for you.",
  "Joy to the world, and to us.",
  "Our little winter wonderland.",
  "You make my heart so full.",
  "All I want for Christmas is you.",
  "Cozy moments, warm hearts.",
  "Love multiplies at Christmas.",
  "The best gift is togetherness.",
  "Making memories, one moment at a time.",
  "You're my favorite tradition.",
  "Peace, love, and Christmas cheer.",
  "Every day with you feels like Christmas.",
];

export const longWishes = [
  "May your holidays be full of warmth, laughter, and the kind of moments you tuck into your heart forever. Merry Christmas!",
  "From our home to yours — may the season bring you peace, sweet surprises, and time with the ones you love.",
  "Wishing you cozy nights, bright mornings, and a year ahead wrapped in love.",
  "A little snow, a lot of love — Merry Christmas to every beautiful soul out there.",
  "To my dear ones: may your cup overflow with joy and your days be gentle.",
  "Here's to laughter around the table, warmth by the fire, and love in every corner. Merry Christmas!",
  "May this season fill your home with joy, your heart with love, and your life with laughter.",
  "Sending you all the magic and wonder that Christmas brings. You deserve every bit of happiness.",
  "Christmas isn't just a day, it's a feeling. Wishing you that feeling all year long.",
  "May the spirit of Christmas bring you peace, the gladness of Christmas give you hope, and the warmth of Christmas grant you love.",
  "To the nights that turned into mornings with friends that turned into family — Merry Christmas!",
  "Wishing you a season filled with warm moments and cherished memories.",
  "May your Christmas sparkle with moments of love, laughter, and goodwill.",
  "Here's to hot chocolate, warm blankets, and the people who make life worth living.",
  "Merry Christmas to you and yours. May your days be merry and bright.",
  "From our family to yours, wishing you peace, joy, and all the blessings of Christmas.",
  "May the magic of Christmas fill every corner of your heart and home.",
  "Wishing you twelve months of success, 52 weeks of laughter, and infinite moments of love.",
  "This Christmas, may you be surrounded by the warmth of family, the joy of the season, and the peace of knowing you are loved.",
  "Sending you a little Christmas magic. May it light up your holidays and carry you into a wonderful new year.",
];

export const writeUpSuggestions = [
  "Our first Christmas together. Forever grateful for this journey.",
  "Making new traditions with my favorite people.",
  "Christmas morning magic captured in one perfect moment.",
  "The best gift of all is being together.",
  "Found my happy place right here, right now.",
  "Every year, a new memory. This one's extra special.",
  "Home for the holidays, exactly where I belong.",
  "The warmth of family makes every Christmas brighter.",
  "Creating memories that will last a lifetime.",
  "Nothing beats Christmas with the ones you love most.",
];
